mode: train

train:
  random_seed: 42
  mode: temporal_unrolling
  # We pick here the simplest NN class
  model_cls: FokkerPlanck2D_NN_AD
  model_cls_kwargs:
    ensure_non_negative_f: true
    guard_cells: true
    # These are NN parameters
    width_size: 64
    depth: 2
    activation: torch.nn.LeakyReLU
    use_bias: true
    use_final_bias: true
  data:
    folders:
      - examples/dataset/normal_-2_0/f
      - examples/dataset/ring_normal_2_0.2/f
    train_valid_ratio: 0.95
  dataset_cls: TemporalUnrolledDataset
  dataset_cls_kwargs:
    step_size: 1
    i_start: 5
  dataloader_cls: null
  temporal_unrolling_stages:
    stage-1-0:
      unrolling_steps: 1
      epochs: 500
      lr: 0.001
    stage-1:
      unrolling_steps: 1
      epochs: 500
      lr: 0.0001
    stage-2:
      unrolling_steps: 2
      epochs: 200
      lr: 0.0001
    stage-5:
      unrolling_steps: 5
      epochs: 200
      lr: 0.0001
    stage-10:
      unrolling_steps: 10
      epochs: 500
      lr: 0.0001
  callbacks:
    log_best_model:
      enabled: true
      frequency: stage_end
    log_best_stage_model:
      enabled: true
    plot_best_stage_model:
      enabled: true
    plot_best_final_model:
      enabled: true
    plot_model_start:
      enabled: true
  optimizer_cls: torch.optim.Adam
  loss:
    name: 'mae'
    mode: 'accumulated'