mode: train

train:
  random_seed: 42
  # by default run on gpu
  device: cuda
  # use temporal unrolling during training
  # more info in temporal_unrolling_stages
  mode: temporal_unrolling
  # which model class to use
  # see classes implemented in models/fp2d
  # the one below is the simplest one
  # it does not enforce any symmetries
  model_cls: FokkerPlanck2D
  model_cls_kwargs: # corresponding class kwargs
    ensure_non_negative_f: true
  # which data to use for training
  data:
    folders:
      - examples/dataset/normal_-2_0/f
      - examples/dataset/ring_normal_2_0.2/f
    train_valid_ratio: 0.95 # can use part for validation
  # which dataset class to use
  # see classes implemented in datasets/
  # for mode=temporal_unrolling this is the one to use
  dataset_cls: TemporalUnrolledDataset
  dataset_cls_kwargs:
    step_size: 1
    i_start: 5
  dataloader_cls: null  # null = all data loaded to memory
  # dataloader_cls_kwargs: # if a cls is provided, args are passed as folows 
  #   param_1: value_1
  #   param_2: value_2
  # you can define multiple training stages
  # each stage should have the values below defined:
  #   unrolling_steps - number of steps the FP solver does before backpropagation
  #   epochs - how many epochs the stage lasts
  #   lr (optional) - learning rate for that particular stage
  temporal_unrolling_stages:
    stage-1:
      unrolling_steps: 1
      epochs: 1000
    stage-2:
      unrolling_steps: 2
      epochs: 200
    stage-5:
      unrolling_steps: 5
      epochs: 200
    stage-10:
      unrolling_steps: 10
      epochs: 500
  # you shouldn´t have to touch these
  # these are callbacks triggered during the training
  callbacks:
    log_best_model: # logs current best model to a checkpoint file
      enabled: true
      frequency: stage_end # only at the end of each stage
    log_best_stage_model:  # logs best model of the corresponding stage
      enabled: true
    plot_best_stage_model: # plots the best model of the corresponding stage
      enabled: true
    plot_best_final_model: # plots best model over the full training
      enabled: true
  # optimizer to use (should not have to change)
  optimizer_cls: torch.optim.Adam
  optimizer_cls_kwargs:
    lr: 0.001
  # loss to use (should not have to change)
  # mae (mean absolute error) or mse (mean squared error)
  loss:
    name: 'mae'
    mode: 'accumulated'
