from .base import FokkerPlanck2DNNBase
from .default import FokkerPlanck2DNN
from .AtBt import FokkerPlanck2DNN_AtBt
from .AsymBsym import FokkerPlanck2DNN_AsymBsym
from .AquadBquad import FokkerPlanck2DNN_AquadBquad
from .AlineBline import FokkerPlanck2DNN_AlineBline
from .ArBquad import FokkerPlanck2DNN_ArBquad
from .ArBline import FokkerPlanck2DNN_ArBline
from .ArBr import FokkerPlanck2DNN_ArBr
from .AquadBquad_ZeroCenter import FokkerPlanck2DNN_AquadBquad_ZeroCenter
from .AquadBquad_center_v import FokkerPlanck2DNN_AquadBquad_CenterV
