mode: train

train:
  dataset:
    train:
      folder:
        - data/finite_size/0-only-electrons/simulations/linear/data/9/FDIST/2D/uniform_0
      i_end:
    valid:
      folders: 
        - data/finite_size/0-only-electrons/simulations/linear/data/9/FDIST/2D/normal_0
    test:
      folders: null
  dataset_cls: src.datasets.BaseDataset
  dataset_cls_kwargs:
    
    step_size: 1
  dataloader_kwargs: null
  epochs: 1000
  optimizer:
    learning_rate: 0.01
