mode: test

test:
  dataset:
    train:
      folders: null
    valid:
      folders: null
    test:
      folders:
        - data/finite_size/0-only-electrons/simulations/linear/data/9/FDIST/2D/uniform_0
    step_size: 1
  model:
    experiment_name: main
    run_name: exp1